name: Benchmarks

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down
  RUST_BACKTRACE: 1

jobs:
  benchmarks:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # we only use macos for fast testing
        os: [macos-latest, windows-latest]
        python-version: ['3.13']

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Rust
        run: rustup show

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      
      - name: Put MSYS2_MinGW64 on PATH
        if: ${{ matrix.os == 'windows-latest' }}
        # there is not yet an environment variable for this path from msys2/setup-msys2
        run: echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Set up libjxl (Windows)
        uses: msys2/setup-msys2@v2
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          update: true
          install: >-
            mingw-w64-x86_64-libjxl

      - name: Set up libjxl (MacOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install jpeg-xl

      - name: Run benchmarks scripts
        run: |
          pip install -e .
          python benchmarks/benchmarks_encode.py -i test/images/bench.png -o benchmarks-results-${{ matrix.os }}-py${{ matrix.python-version }}.json

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: benchmarks-results-${{ matrix.os }}-py${{ matrix.python-version }}
          path: benchmarks-results-${{ matrix.os }}-py${{ matrix.python-version }}.json
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}


